import os

class Config:
    DEBUG = os.getenv("FLASK_DEBUG", "False") == "True"
    HOST = os.getenv("FLASK_HOST", "127.0.0.1")
    PORT = int(os.getenv("FLASK_PORT", "5000"))
    SECRET_KEY = os.getenv("SECRET_KEY")
    HAS_VALID_EMAIL = os.getenv("HAS_VALID_EMAIL", "False") == "True"
    EMAIL_SENDER = os.getenv("EMAIL_SENDER")
    EMAIL_PASSWORD = os.getenv("EMAIL_PASSWORD")

    SCHEDULER_INTERVAL_SECONDS = 60
    
    TEMPORARY_ROUTES_EXPIRY_SECONDS = 300
    HTTP_STATUS_NOT_FOUND = 404

    LEGITIMATE_STATUS = 0
    SUSPICIOUS_STATUS = 0.5
    PHISHING_STATUS = 1

    COMPLETE_SITE_ANALYSIS = 1
    COMPREHENSIVE_ANALYSIS = 2
    FOCUSED_ANALYSIS = 3
    QUICK_ANALYSIS = 4
    HTTP_STATUS_OK = 200

    URL_LENGTH_SUSPICIOUS_TRESHOLD_MIN = 54
    URL_LENGTH_SUSPICIOUS_TRESHOLD_MAX = 75
    SUBDOMAIN_COUNT_LEGITIMATE_MAX = 1
    SUBDOMAIN_COUNT_SUSPICIOUS = 2
    HTTPS_PORT = 443
    MINIMUM_REGISTRATION_DURATION_FOR_LEGITIMACY = 365
    SOCKET_CONNECTION_TIMEOUT = 1
    EXTERNAL_REQUEST_RATIO_SUSPICIOUS_THRESHOLD_MIN = 22.0
    EXTERNAL_REQUEST_RATIO_SUSPICIOUS_THRESHOLD_MAX = 61.0
    ANCHOR_DOMAIN_SIMILARITY_SUSPICIOUS_THRESHOLD_MIN = 31.0
    ANCHOR_DOMAIN_SIMILARITY_SUSPICIOUS_THRESHOLD_MAX = 67.0
    TAG_LINKS_CONGRUENCE_SUSPICIOUS_THRESHOLD_MIN = 17.0
    TAG_LINKS_CONGRUENCE_SUSPICIOUS_THRESHOLD_MAX = 81.0
    REDIRECTIONS_COUNT_LEGITIMATE_MAX = 1
    REDIRECTIONS_COUNT_SUSPICIOUS_MIN = 2
    REDIRECTIONS_COUNT_SUSPICIOUS_MAX = 3

    THRESHOLD = 0.5
    
    SMTP_SSL_PORT = 465